bookers2-debug/config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  root 'homes#top'
  get 'home/about' => 'homes#about', as: 'about'
  
  resources :users, only: [:show,:index,:edit,:update]
  resources :relationships, only: [:create, :destroy]
  
  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end 
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  
end

bookers2-debug/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

bookers2-debug/app/models/book.rb
class Book < ApplicationRecord
	

	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
	belongs_to :user
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

bookers2-debug/app/models/book_comment.rb
class BookComment < ApplicationRecord
    
    belongs_to :user
    belongs_to :book
    
    validates :comment, presence: true
end

bookers2-debug/app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end
 

bookers2-debug/app/models/relationship.rb
class Relationship < ApplicationRecord
    
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
    
    validates :follower_id, presence: true
    validates :followed_id, presence: true
end

bookers2-debug/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  
  has_many :following, through: :relationships, source: :followed
  has_many :followers, through: :relationships, source: :follower
  
  attachment :profile_image

  validates :name, presence: true, length: { in: 2..20}
  validates :introduction, length: {maximum: 50}
  
  def follow(other_user)
    following << other_user
  end

  
  def unfollow(other_user)
    relationships.find_by(followed_id: other_user.id).destroy
  end


  def following?(other_user)
    following.include?(other_user)
  end
  
  
end

bookers2-debug/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	
	before_action :configure_permitted_parameters, if: :devise_controller?

  
  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :name])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    
  end
end

bookers2-debug/app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
    
    def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_back(fallback_location: root_path)
    end
    
    def destroy
        BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
        redirect_back(fallback_location: root_path)
    end 
    
    private
    def book_comment_params
        params.require(:book_comment).permit(:comment)
    end 
end

bookers2-debug/app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :authenticate_user!
before_action :edit_book, only: [:edit, :update]

  def show
    @book = Book.find(params[:id])
    @new_comment = BookComment.new
  end

  def index
    @books = Book.all
    @book = Book.new
    @new_comment = BookComment.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_back(fallback_location: root_path)
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def edit_book
    unless Book.find(params[:id]).user.id.to_i == current_user.id
      redirect_to books_path
    end
  end
end

bookers2-debug/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    
    def create
      book = Book.find(params[:book_id])
      favorite = current_user.favorites.new(book_id: book.id)
      favorite.save
      redirect_back(fallback_location: root_path)
    end

    def destroy
      book = Book.find(params[:book_id])
      favorite = current_user.favorites.find_by(book_id: book.id)
      favorite.destroy
      redirect_back(fallback_location: root_path)
    end
    
end

bookers2-debug/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

bookers2-debug/app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  
  def create
    user = User.find(params[:user_id])
    relationship = current_user.relationships.new(user_id: user.id)
    
    user.relationships.create(followed_id: other_user.id)
    relationship.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    user = User.find(params[:user_id])
    relationship = current_user.relationships.find_by(user_id: user.id)
    relationship.destroy
    redirect_back(fallback_location: root_path)
  end
  
  
end

bookers2-debug/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:update, :edit]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @books = @user.books
    @book = Book.new
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end
  
  def following
    @title = "Follow Users"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end
  
  def followers
    @title = "Follower Users"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

bookers2-debug/app/helpers/application_helper.rb
module ApplicationHelper
end

bookers2-debug/app/helpers/books_helper.rb
module BooksHelper
end

bookers2-debug/app/helpers/favorites_helper.rb
module FavoritesHelper
end

bookers2-debug/app/helpers/homes_helper.rb
module HomesHelper
end

bookers2-debug/app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

bookers2-debug/app/helpers/relationships_helper.rb
module RelationshipsHelper
end

bookers2-debug/app/helpers/users_helper.rb
module UsersHelper
end

bookers2-debug/app/views/books/_form.html.erb
<%= form_with model:book, local:true do |f| %>
  <% if book.errors.any? %>
    <% book.errors.full_messages.each do |message| %>
      <li>error <%= message %></li>
    <% end %>
  <% end %>
  <div class="field row">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'col-xs-12 book_title' %>
  </div>

  <div class="field row">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'col-xs-12 book_body' %>
  </div>

  <div class="actions row">
    <%= f.submit class: 'btn btn-primary col-xs-12' %>
  </div>
<% end %>

bookers2-debug/app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>

bookers2-debug/app/views/books/edit.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">

		<h1>Editing Book</h1>

		<%= render "books/form", book: @book %>
		<%= link_to "Show", book_path(@book), class: "book_#{@book.id}" %>
		<%= link_to "Back", books_path, class: "back" %>

	</div>
	<div class="col-md-3"></div>

</div>

bookers2-debug/app/views/books/index.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>

		<h2>New book</h2>
		<%= render 'books/form', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Books</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to user_path(book.user) do %>
							<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>
						<td><% if book.favorited_by?(current_user) %>
							<li>
							  <%= link_to book_favorites_path(book), method: :delete do %>
							    <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
							    <%= book.favorites.count %>
							  <% end %>
							</li>
							<% else %>
							<li>
							  <%= link_to book_favorites_path(book), method: :post do %>
							    <i class="fa fa-heart-o" aria-hidden="true"></i>
							    <%= book.favorites.count %>
							  <% end %>
							</li>
						<% end %>
					</td>
					<td><%=  "コメント数: #{book.book_comments.count}" %></td>
				</tr>
				<% end %>
			</tbody>
		</table>

		<!--books一覧 -->


	</div>
</div>

bookers2-debug/app/views/books/show.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>

		<h2>New book</h2>
		<%= render 'books/form', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Book detail</h2>

		<table class="table">
				<tr>
					<td>
						<%= link_to user_path(@book.user) do %>
							<%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
							<%= @book.user.name %>
						<% end %>
					</td>
					<td><%= link_to @book.title, book_path(@book) %></td>
					<td><%= @book.body %></td>
					<td><% if @book.favorited_by?(current_user) %>
							<li>
							  <%= link_to book_favorites_path(@book), method: :delete do %>
							    <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
							    <%= @book.favorites.count %>
							  <% end %>
							</li>
							<% else %>
							<li>
							  <%= link_to book_favorites_path(@book), method: :post do %>
							    <i class="fa fa-heart-o" aria-hidden="true"></i>
							    <%= @book.favorites.count %>
							  <% end %>
							</li>
						<% end %>
					</td>
					<td>コメント数:<%= @book.book_comments.count %></td>
					<% if @book.user.id == current_user.id %>
						<td><%= link_to "Edit", edit_book_path(@book), class: "btn-sm btn-success" %></td>
						<td><%= link_to "Destroy", book_path(@book), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>
					<% end %>
				</tr>
			</table>
			<ul>
				<li>
					<% @book.book_comments.each do |book_comment| %>
						<%= attachment_image_tag(book_comment.user, :profile_image, format: 'jpg', fallback: "no_image.jpg", size: "40x40") %>
						<%= book_comment.user.name %>
						<%= book_comment.comment %>
						<% if book_comment.user == current_user %>
							<%= link_to "削除", book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn btn-danger pull-right" %>
						<% end %>
					<% end %>
				</li><br>
			</ul>
			<!-- <form class="mt-20"> -->
			<%= form_with(model:[@book, @new_comment], local: true) do |f| %>
			  <div class="row">
			    <div class="col-sm-12">
			      <%= f.text_area :comment, class: "form-control",placeholder: "コメントをここに" %>
			    </div>
			  </div>
			  <%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
			<% end %>
			<!-- </form> -->

	</div>
</div>

bookers2-debug/app/views/homes/about.html.erb
<h1>Welcome to <span class='glyphicon glyphicon-book'></span><strong>Bookers</strong>!</h1>

bookers2-debug/app/views/homes/top.html.erb
<div class="row">
  <div class='top-message col-xs-offset-3 col-xs-6'>
    <h1>welcome to <span class='glyphicon glyphicon-book'></span><strong>Bookers</strong>  !!</h1>
    <p>In  <span class='glyphicon glyphicon-book'></span><strong>Bookers</strong>, </p>
    <p>you can share and exchange  your opinions , inpressions , and emotions</p>
    <p> about various books!</p>

    <div class="btn-wrapper">
      <div class="row">
        <p><%= link_to 'Log in', new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1" %></p>
      </div>
      <div class="row">
        <p><%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1" %></p>
      </div>
    </div>

  </div>
</div>

bookers2-debug/app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>

    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

bookers2-debug/app/views/layouts/_footer.html.erb
<footer>
  <div class='container'>
  	<div class='row'>
    	<div class='col-xs-3 col-xs-offset-9'>
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

bookers2-debug/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav class='nav navbar-nav navbar-left' >
      <span>Bookers</span>
    </nav>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to ' Home', user_path(current_user), class: 'glyphicon glyphicon-home home' %></li>
          <li><%= link_to ' Users', users_path, class: 'glyphicon glyphicon-user users' %></li>
          <li><%= link_to ' Books', books_path, class: 'glyphicon glyphicon-book books'%></li>
          <li><%= link_to ' logout', destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out logout' %></li>
        <% else %>
          <li><%= link_to ' Home', root_path, class: 'glyphicon glyphicon-home home' %></li>
          <li><%= link_to ' About', about_path, class: 'glyphicon glyphicon-link about' %></li>
          <li><%= link_to ' sign up', new_user_registration_path, class: 'glyphicon glyphicon-edit sign_up' %></li>
          <li><%= link_to ' login', new_user_session_path, class: 'glyphicon glyphicon-log-in sign_in'%></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

bookers2-debug/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2-debug</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/4d0aeef251.js" crossorigin="anonymous"></script>

  </head>


  <body>
    <%= render 'layouts/header' %><br><br><br>
    
    <div class="container">
      <p id="notice"><%= notice %></p>
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>

bookers2-debug/app/views/users/_follow.html.erb
<%= form_for(current_user.relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "フォローする", class: "btn btn-primary" %>
<% end %>

bookers2-debug/app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

bookers2-debug/app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

bookers2-debug/app/views/users/_profile.html.erb
<table class="table">
	<tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>

	<tr>
		<th>name</th>
		<th><%= user.name %></th>
	</tr>

	<tr>
		<th>introduction</th>
		<th><%= user.introduction %></th>
	</tr>
	<tr>
		<th>follows</th>
		<th><%= user.following.count %></th>
	</tr>
	<tr>
		<th>followers</th>
		<th><%= user.followers.count %></th>
	</tr>
	
</table>

<div class="row">
  <% if user == current_user %>
	<%= link_to '', edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
  <% else %>
    <%= render 'follow_form' if logged_in? %>
  <% end %>
</div>

bookers2-debug/app/views/users/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "フォローを外す", class: "btn" %>
<% end %>

bookers2-debug/app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_with model:@user, local: true do |f| %>

	<!-- エラーメッセージ表示-->
	<% if @user.errors.any? %>
		<div id="error_explanation">
			<h3><%= @user.errors.count %>error prohibited this obj from being saved:</h3>
			<ul>
				<% @user.errors.full_messages.each do |message| %>
				<li>error<%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<!-- エラーメッセージ表示-->
	
	<label>Name </label><%= f.text_field :name %><br>
	<label>Image </label><%= f.attachment_field :profile_image %><br>
	<label>Introduction </label><%= f.text_area :introduction %>
	<div class="actions">
		<%= f.submit 'Update User' %>
	</div>

<% end %>

bookers2-debug/app/views/users/index.html.erb
<div class="row">
	<div class="col-xs-3">
	
		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>
		
		<h2>New book</h2>
		<%= render 'books/form', book: @book %>
	</div>
	<div class="col-xs-9">	
		<h2>Users</h2>
		<!--users一覧 -->
		<table class="table">
			<thead>
				<tr>
					<th>image</th>
					<th>name</th>
					<th colspan="3"></th>
				</tr>
			</thead>
		
			<tbody>
				<% @users.each do |user| %>
				<tr>
					<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
					<td><%= user.name %></td>
					<td>フォロー数:<%= user.following.count %></td>
					<td>フォロワー数:<%= user.followers.count %></td>
					<td><%= render 'follow_form' if logged_in? %></td>
					<td><%= link_to "Show", user_path(user), class: "user_#{user.id}" %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<!--users一覧 -->
	</div>
</div>
		

bookers2-debug/app/views/users/show.html.erb
<div class="row">
	<div class="col-xs-3">
		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>

		<h2>New book</h2>
		<%= render 'books/form', book: @book %>
	</div>

	<div class="col-xs-9">
		<h2>Books</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
					<tr>
						<td>
							<%= link_to user_path(book.user) do %>
								<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
							<% end %>
						</td>
						<td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
						<td><%= book.body %></td>
						<td>コメント数:<%= book.book_comments.count %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
		<!--books一覧 -->
	</div>
</div>

bookers2-debug/app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <div class="col-md-12">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>